"""parameters for PE regressors experiment."""
design_name = 'sim_beta'
temporal_deriv = False
contrasts = [
('b_plus0',['b_plus0'],[1]), 
('b_plus1',['b_plus1'],[1]),
('b_plus2',['b_plus2'],[1]),
('b_plus3',['b_plus3'],[1]),
('b_plus4',['b_plus4'],[1]),
('b_plus5',['b_plus5'],[1]),
('b_plus6',['b_plus6'],[1]),
('b_plus7',['b_plus7'],[1]),
('b_plus8',['b_plus8'],[1]),
('b_plus9',['b_plus9'],[1]),
('c_plus0',['c_plus0'],[1]), 
('c_plus1',['c_plus1'],[1]),
('c_plus2',['c_plus2'],[1]),
('c_plus3',['c_plus3'],[1]),
('c_plus4',['c_plus4'],[1]),
('c_plus5',['c_plus5'],[1]),
('c_plus6',['c_plus6'],[1]),
('c_plus7',['c_plus7'],[1]),
('c_plus8',['c_plus8'],[1]),
('c_plus9',['c_plus9'],[1]),
('c_minus0',['c_minus0'],[1]), 
('c_minus1',['c_minus1'],[1]), 
('c_minus2',['c_minus2'],[1]), 
('c_minus3',['c_minus3'],[1]), 
('c_minus4',['c_minus4'],[1]), 
('c_minus5',['c_minus5'],[1]), 
('c_minus6',['c_minus6'],[1]), 
('c_minus7',['c_minus7'],[1]), 
('c_minus8',['c_minus8'],[1]), 
('c_minus9',['c_minus9'],[1]), 
('b_minus0',['b_minus0'],[1]), 
('b_minus1',['b_minus1'],[1]), 
('b_minus2',['b_minus2'],[1]), 
('b_minus3',['b_minus3'],[1]), 
('b_minus4',['b_minus4'],[1]), 
('b_minus5',['b_minus5'],[1]), 
('b_minus6',['b_minus6'],[1]), 
('b_minus7',['b_minus7'],[1]), 
('b_minus8',['b_minus8'],[1]), 
('b_minus9',['b_minus9'],[1])]